apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-auth

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - pod-monitor.yaml
    - secrets/db-creds.yaml
    - secrets/db.yaml
    - secrets/misc.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: auth
          component: api

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: auth-api
      newName: ghcr.io/sweetrpg/auth-api
      newTag: latest
