---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: auth-api-db

spec:
  refreshInterval: 12h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: api-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /sweetrpg/auth/api/db
      rewrite:
        - regexp:
            source: "DB_PASSWORD"
            target: "DB_PW"
