apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-auth

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml

labels:
    - pairs:
          app.kubernetes.io/name: auth-api
          app.kubernetes.io/version: v1
          app.kubernetes.io/component: api
          app.kubernetes.io/part-of: auth
          com.sweetrpg/env: local
      includeSelectors: false
      includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: auth-api
      newName: ghcr.io/sweetrpg/auth-api
      newTag: latest
