// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://pilgrimagesoftware.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://sweetrpg.com",
            "email": "admin@sweetrpg.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/deny-entries/{subject}": {
            "post": {
                "description": "Deny a subject access to a service",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Deny a subject access to a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth0 subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service to deny",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.denyEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "204": {
                        "description": "No Content - deny entry already present"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            }
        },
        "/api/admin/deny-entries/{subject}/{service}": {
            "delete": {
                "description": "Remove a subject's service deny entry",
                "tags": [
                    "admin"
                ],
                "summary": "Remove a subject's service deny entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth0 subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service to un-deny",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            }
        },
        "/api/admin/roles": {
            "get": {
                "description": "Bulk lookup of roles/deny-entries by subject",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Bulk lookup of roles/deny-entries by subject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated Auth0 subjects",
                        "name": "subjects",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.subjectRolesSummary"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            }
        },
        "/api/admin/roles/{subject}": {
            "get": {
                "description": "Get a subject's roles and deny entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get a subject's roles and deny entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth0 subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.subjectRolesSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a role to a subject",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Add a role to a subject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth0 subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Role to add",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.roleAssignmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "204": {
                        "description": "No Content - role already present"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            }
        },
        "/api/admin/roles/{subject}/{role}": {
            "delete": {
                "description": "Remove a role from a subject",
                "tags": [
                    "admin"
                ],
                "summary": "Remove a role from a subject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shared internal-service secret",
                        "name": "X-Internal-Service-Token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Acting admin's Auth0 sub, for audit attribution",
                        "name": "X-Acting-User-Sub",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth0 subject",
                        "name": "subject",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role to remove",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/vo.ErrorVO"
                        }
                    }
                }
            }
        },
        "/authz/check": {
            "post": {
                "description": "Authorize a service request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authz"
                ],
                "summary": "Authorize a service request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cAuth0 access token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Service to check access for",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.authzCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.authzDeniedResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.authzErrorResponse"
                        }
                    }
                }
            }
        },
        "/status/health": {
            "get": {
                "description": "Health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.HealthResponseVO"
                        }
                    }
                }
            }
        },
        "/status/ping": {
            "get": {
                "description": "Ping",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.PingResponseVO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.authzAllowedResponse": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "server.authzCheckRequest": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "server.authzDeniedResponse": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "server.authzErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "server.denyEntryRequest": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "service": {
                    "type": "string"
                }
            }
        },
        "server.roleAssignmentRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "server.subjectRolesSummary": {
            "type": "object",
            "properties": {
                "deniedServices": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "vo.ErrorVO": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "vo.HealthResponseVO": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "database": {
                    "type": "string"
                },
                "errors": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ping": {
                    "type": "string"
                }
            }
        },
        "vo.PingResponseVO": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Auth API service",
	Description:      "Swagger APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
